### ISSUE TITLE
Using Vue Events

### ISSUE THREAD

**Issue by ecmel** [lokyoung/vuejs-paginate#9]
Hi, instead of `:clickHandler` a custom Vue event can be used with `.$emit` such as `@changed`

**Comment by lokyoung** [comment]
Hi @ecmel . I think it's good for us to use Vue event. But i need to consider. Because `:clickHandler` works well too. If we change that, we need to change the api of our package. So the user need to make changes in their code. Not sure it's appropriate to make this changes. Thanks for your understanding.
